version: "3"
services:
  api:
    container_name: squid-api
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASS=postgres
      - GQL_PORT=4350
    command: ["sqd", "serve:prod"]
    network_mode: "host"
  processor:
    container_name: squid-processor
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASS=postgres
      - ACCOUNT_ADDRESSES=????
      - FROM_BLOCK=????
      - CHAIN_RPC=????
    command: ["sqd", "process:prod"]
    network_mode: "host"